id: A13F43013
base_file: f5669.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:20:22.345413
  last_modified_at: 2022-06-11 13:20:22.345419
