id: A13F43013
base_file: f66A0.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:20:22.355112
  last_modified_at: 2022-06-11 13:20:22.355119
