id: A13F43013
base_file: f6FAC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:20:22.388848
  last_modified_at: 2022-06-11 13:20:22.388855
